_target_: src.models.deepmtlr_model.DEEP_MTLR

model: "Dual"
dense_factor : 1 #Factor to multiply width of fc layer.
n_dense : 2   #Number of fc layers.
dropout : 0.2
C1 : 1 #Regularization term for MTLR backprop.
lr : 0.016
weight_decay: 0.00001

#CNN
k1 : 3
k2 : 5